/*
Este Formulario contiene la tabla donde se muestra el historial de los ganadores de todas las partidas jugadas
Y tiene el método que llena la tabla con los datos del archivo Puntaje.dat
 */
package Formularios;

import java.awt.Color;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ListIterator;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import uno.Archivo;
import uno.Jugador;

/**
 *
 * @author Fernández
 */
public class MostrarPuntos extends javax.swing.JFrame {

    private Image icono;
    private DefaultTableModel modelo; 
    private SimpleDateFormat formato; 

    /**
     * Creates new form MostrarPuntos
     */
    public MostrarPuntos() {
        initComponents();
        formato = new SimpleDateFormat("dd/MM/yyyy");
    }

    public void llenaTabla() {
        Object objeto[] = new Object[3];
        ListIterator<Jugador> listIte = Archivo.listaGanadores.listIterator(); 

        while (listIte.hasNext()) {
            Jugador datoJugador = listIte.next();
            objeto[0] = datoJugador.getNombre();
            objeto[1] = datoJugador.getPuntaje();
            objeto[2] = formato.format(datoJugador.getFecha());

            modelo.addRow(objeto);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMostrarPuntajes = new javax.swing.JTable();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historial de Ganadores");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 210, 50));

        btnVolver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVolver.setText("Volver ");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 210, 50));

        jTableMostrarPuntajes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTableMostrarPuntajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableMostrarPuntajes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTableMostrarPuntajes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 380));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo mostrar puntos.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuPrincipal ventana1 = new MenuPrincipal();
        ventana1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);

        icono = new ImageIcon(getClass().getResource("/Imagenes/iconUno.png")).getImage();
        setIconImage(icono);

        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre del Jugador");
        modelo.addColumn("Puntaje");
        modelo.addColumn("Fecha");

        jTableMostrarPuntajes.setModel(modelo);
        jTableMostrarPuntajes.setEnabled(false);

        jTableMostrarPuntajes.setGridColor(Color.BLACK);
        
        jTableMostrarPuntajes.setForeground(Color.BLUE);

        llenaTabla();
        
    }//GEN-LAST:event_formWindowOpened

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MostrarPuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MostrarPuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MostrarPuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MostrarPuntos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MostrarPuntos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMostrarPuntajes;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
